import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { ThemeProvider } from "@/components/Theme/ThemeProvider";
import Switchnav from "@/components/Nav/Switchnav";



export const metadata: Metadata = {
  title: "EDUPATH WEBAPP",
  description: "Generated by create next app",
};


type RootLayoutpropstype =  Readonly<{
  children: ReactNode;
}>

 const RootLayout=({
  children,
}:RootLayoutpropstype) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
          <ThemeProvider
           attribute="class"
           defaultTheme="light"
           enableSystem>
       <Switchnav/>
        <main>
        {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
